### ISSUE TITLE
Browserify has trouble with not finding ./lib-cov/extend

### ISSUE THREAD

**Issue by ghost** [logicalparadox/tea-error#1]
This two lines cause trouble with Browserify because the file doesn't exist: https://github.com/qualiancy/tea-error/blob/master/index.js#L1-L2
I guess that browserify considers all paths.

After changing the content of index.js to:

```
module.exports = require('./lib/extend');
```

it worked.

Can you maybe consider another strategy to do this. Maybe creating a index-cov.js with the content:

```
module.exports = require('./lib-cov/extend');
```

**Comment by logicalparadox** [comment]
@Sanjo Try release `0.2.0` ... should be much better.
